###
http://localhost:6060/api


###
GET http://localhost:6060/api/admin


###
GET http://localhost:6060/api/admin/641a9cb560adceff6ea5664d


###
POST http://localhost:6060/api/admin/register
Content-Type: application/json

    {       
        "firstName": "aaaa" ,
        "lastName": "a" ,
        "userName": "a" ,
        "email": "aaaaa@gmail.com" ,
        "phone": 12 ,
        "image": "a" ,
        "password": "a"
    }

###
POST http://localhost:6060/api/admin/login
Content-Type: application/json

    {       
        "email": "aaaaa@gmail.com",
        "password": "a"
    }


###
PUT http://localhost:6060/api/admin/641a9cb560adceff6ea5664d
Content-Type: application/json

    {       
        "firstName": "a" ,
        "lastName": "" ,
        "userName": "" ,
        "email": "" ,
        "phone": 0 ,
        "image": "" ,
        "password": ""
    }


###
DELETE http://localhost:6060/api/admin/641a9cb560adceff6ea5664d
