###
GET http://localhost:6060/api/category


###
GET http://localhost:6060/api/category/641a9d7760adceff6ea56660


###
POST http://localhost:6060/api/category
Content-Type: application/json

    {
        "categoryName": "",
        "categoryLink": ""
    }

###
PUT http://localhost:6060/api/category/641a9d7760adceff6ea56660
Content-Type: application/json

    {
        "categoryName": "a",
        "categoryLink": ""
    }


###
DELETE http://localhost:6060/api/category/64191467a9769edcf0656d0e
