###

GET http://localhost:6060/api

###

GET  http://localhost:6060/api/product/7b7a60e3-ac0c-44a9-923a-5e1e26990fd8

###

GET http://localhost:6060/api/product

###

POST http://localhost:6060/api/product
Content-Type: application/json

{
    "productName": "aasqsssa",
    "categoryId": "641a9d7760adceff6ea56660",
    "brandId": "641a9d6260adceff6ea5665b",
    "price": "",
    "salePercent": "",
    "description": "",
    "quantity": "",
    "thumbImage": "",
    "images": [],
    "createdAdmin": "641bb8a9e3b5aa4a75923ad6"
}

###

PUT http://localhost:6060/api/product/641d0b071f674b4422413210
Content-Type: application/json

{
    "productName": "aasqsssa",
    "categoryId": "641a9d7760adceff6ea56660",
    "brandId": "641a9d6260adceff6ea5665b",
    "price": "",
    "salePercent": "",
    "description": "",
    "quantity": "",
    "thumbImage": "",
    "images": [],
    "createdAdmin": "641bb8a9e3b5aa4a75923ad6"
}

###

DELETE http://localhost:6060/api/product/641d0b071f674b4422413210