###

GET http://localhost:6060/api

###

GET  http://localhost:6060/api/user/1

###

GET http://localhost:6060/api/user?limit10

###

POST http://localhost:6060/api/user
Content-Type: application/json

{
    "firstname": "",
    "lastname": "",
    "username": "",
    "email": "",
    "phone": "",
    "image": "",
    "password": ""
}

###

PUT http://localhost:6060/api/user/1
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "username": "",
    "email": "",
    "phone": "",
    "image": "",
    "password": ""
}

###

DELETE http://localhost:6060/api/user/9cc9b77a-6f30-4eec-ac57-1b9912374d98