###

GET http://localhost:6060/api

###

GET  http://localhost:6060/api/menu

###

GET http://localhost:6060/api/menu/0be6c0c1-c337-4ebf-af98-9d4b113f5247

###

POST http://localhost:6060/api/menu
Content-Type: application/json

{
    "menuName": "",
    "link": "",
    "position": ""
}

###
PUT http://localhost:6060/api/menu
Content-Type: application/json

{
    "id": "ca001679-53b2-4f4b-9a66-28cbde362b52",
    "menuName": "test3",
    "link": "/test3",
    "position" : "6"
}

###

DELETE http://localhost:6060/api/menu/4c1d2975-40ea-414c-8727-dca8b8982e15