###

GET http://localhost:6060/api

###

GET  http://localhost:6060/api/user

###

GET http://localhost:6060/api/user

###

POST http://localhost:6060/api/user
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "phone": "",
    "password": ""
}

###

PUT http://localhost:6060/api/user/9cc9b77a-6f30-4eec-ac57-1b9912374d98
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "phone": "",
    "password": ""
}

###

DELETE http://localhost:6060/api/user/9cc9b77a-6f30-4eec-ac57-1b9912374d98