###

GET http://localhost:6060/api

###

GET  http://localhost:6060/api/customer

###

GET http://localhost:6060/api/customer/f8364a98-d6f5-4b23-8787-556ca2494ba7

###

POST http://localhost:6060/api/customer
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "username": "",
    "phone": "",
    "email": "",
    "password": "" 
}

###
PUT http://localhost:6060/api/customer/f8364a98-d6f5-4b23-8787-556ca2494ba7
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "",
    "username": "",
    "phone": "",
    "email": "",
    "password": ""
}

###

DELETE http://localhost:6060/api/customer/25fde7a2-eecd-4cf3-9aa6-9ad77099acf9